[config]
api_version = "v1.1"
base_url = "https://bittrex.com/api/"
api_key = "<api_key>"
api_secret = "<api_secret>"

base_coin = "BTC"
market_coin = "MONA"
last_sell = 0.00046721
target_sell = 0.02
